### ISSUE TITLE
not working pls fix 

### ISSUE THREAD

**Issue by xeerom** [PhantomDoom741/ThemeMaster#1]

**Comment by xeerom** [comment]
code doesnt work i use windows 93 often and i need this program but it doesnt work for me

**Comment by Driftini** [comment]
Download v1.0, unzip it and import the resulting folder in Windows93 (Don't drop the folder in /a/boot/). Then open Terminal and use the command `js [path of thminstall.js]` (example: `js /a/desktop/ThemeMaster-1.0/thminstall.js`). A window will appear. Accept all the message boxes, Windows93 will reboot. Once the reboot has finished, enter the `themes` command in Terminal to open ThemeMaster.

**Comment by xeerom** [comment]
ok works now
